name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADR }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /deploy
            git pull
            docker compose up -d --build